# Generated by Django 4.1.7 on 2024-05-10 06:06

import colorfield.fields
import course.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Название"
                    ),
                ),
                ("lead", models.TextField(max_length=250, verbose_name="Лид")),
                ("price", models.IntegerField(default=0, verbose_name="Цена")),
                ("introduction", models.TextField(verbose_name="Вступление")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликовано"),
                ),
                (
                    "private",
                    models.BooleanField(
                        default=False, verbose_name="Сделать курс приватным"
                    ),
                ),
                (
                    "access",
                    models.ManyToManyField(
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователи с доступом к курсу",
                    ),
                ),
            ],
            options={
                "verbose_name": "курс",
                "verbose_name_plural": "курс",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Название")),
                ("theory", models.TextField(verbose_name="Теория")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликовано"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course.course",
                        verbose_name="Курс",
                    ),
                ),
            ],
            options={
                "verbose_name": "урок",
                "verbose_name_plural": "уроки",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "background_color",
                    colorfield.fields.ColorField(
                        default="#E94F37",
                        image_field=None,
                        max_length=18,
                        samples=None,
                        verbose_name="Цвет фона",
                    ),
                ),
            ],
            options={
                "verbose_name": "тег",
                "verbose_name_plural": "теги",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Название")),
                (
                    "difficulty",
                    models.IntegerField(
                        choices=[(1, "*"), (2, "**"), (3, "***")],
                        default=1,
                        verbose_name="Сложность",
                    ),
                ),
                (
                    "time_limit",
                    models.IntegerField(
                        default=1,
                        help_text="(секунд)",
                        validators=[course.validators.validate_more_zero],
                        verbose_name="Ограничение времени",
                    ),
                ),
                (
                    "memory_limit",
                    models.IntegerField(
                        default=64,
                        help_text="(Mb)",
                        validators=[course.validators.validate_more_zero],
                        verbose_name="Ограничение памяти",
                    ),
                ),
                (
                    "input_type",
                    models.CharField(
                        default="стандартный ввод или input.txt",
                        max_length=100,
                        verbose_name="Ввод",
                    ),
                ),
                (
                    "output_type",
                    models.CharField(
                        default="стандартный вывод или output.txt",
                        max_length=100,
                        verbose_name="Вывод",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст задания")),
                (
                    "input_format",
                    models.TextField(blank=True, verbose_name="Формат ввода"),
                ),
                (
                    "output_format",
                    models.TextField(blank=True, verbose_name="Формат вывода"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликовано"),
                ),
                (
                    "solution",
                    models.TextField(
                        blank=True,
                        default='<pre class="language-python">&nbsp;</pre>',
                        verbose_name="Решение автора",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course.lesson",
                        verbose_name="Урок",
                    ),
                ),
            ],
            options={
                "verbose_name": "задание",
                "verbose_name_plural": "задания",
            },
        ),
        migrations.CreateModel(
            name="PrivateMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Название")),
                ("text", models.TextField(verbose_name="Текст")),
                (
                    "lead",
                    models.TextField(
                        blank=True, default="", max_length=250, verbose_name="Лид"
                    ),
                ),
                ("price", models.IntegerField(default=0, verbose_name="Цена")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликовано"),
                ),
                (
                    "access",
                    models.ManyToManyField(
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователи с доступом к материалу",
                    ),
                ),
            ],
            options={
                "verbose_name": "приватный материал",
                "verbose_name_plural": "приватные материалы",
            },
        ),
        migrations.CreateModel(
            name="Example",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "input_data",
                    models.TextField(blank=True, null=True, verbose_name="Ввод"),
                ),
                (
                    "output_data",
                    models.TextField(blank=True, null=True, verbose_name="Вывод"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликовано"),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course.task",
                        verbose_name="Задание",
                    ),
                ),
            ],
            options={
                "verbose_name": "пример",
                "verbose_name_plural": "примеры",
            },
        ),
        migrations.AddField(
            model_name="course",
            name="tags",
            field=models.ManyToManyField(to="course.tag", verbose_name="Теги"),
        ),
    ]
