# Generated by Django 5.0.2 on 2024-04-02 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_events_lesson_student_tariff_token_homework_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.tariff'),
        ),
    ]
