# Generated by Django 4.2.11 on 2024-04-25 20:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_token_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 9, 20, 47, 3, 926483, tzinfo=datetime.timezone.utc)),
        ),
    ]
