# Generated by Django 5.0.2 on 2024-04-26 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_token_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 10, 6, 40, 24, 564552, tzinfo=datetime.timezone.utc)),
        ),
    ]
